### ISSUE TITLE
Players joined my game without a code

### ISSUE THREAD

**Issue by d-johnston** [jtamminga/jotto_multi#2]
## Issue
Mysterious Hubby and [heart] Wifey players joined my lobby while testing without having received a code from me

## Steps to reproduce
1. Create a room by clicking Host link and entering name
2. Wait for strangers to join your room

**Comment by jtamminga** [comment]
[fixed issue](https://github.com/jtamminga/jotto_server/commit/fe5f88a670a2753c4793c328a28a34fde0ad832c) with server broadcasting `userConnect` event (only on rejoin game) to all rooms
